name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: ui.spec

    - uses: actions/upload-artifact@v2
      with:
        name: ssbu_amiibo
        path: src/dist/windows # or path/to/artifact